CREATE TABLE IF NOT EXISTS HANDYSUPERMARKET.PASILLOS (
	COD_QR_PASILLO NUMBER(150),
	NOMBRE_PASILLO VARCHAR(40),
	DESCRIPCION VARCHAR(200),
	PHOTO_LOCATION VARCHAR(200),
	
	CONSTRAINT PK_COD_QR_PASILLO PRIMARY KEY (COD_QR_PASILLO)
);

CREATE TABLE IF NOT EXISTS HANDYSUPERMARKET.ESTANTE (
	COD_QR_ESTANTE VARCHAR(150),
	COD_QR_PASILLO NUMBER(150),

	CONSTRAINT PK_COD_QR_ESTANTE PRIMARY KEY (COD_QR_ESTANTE),
	CONSTRAINT FL_COD_QR_PASILLO FOREIGN KEY (COD_QR_PASILLO) REFERENCES PASILLOS(COD_QR_PASILLO)
);

CREATE TABLE IF NOT EXISTS HANDYSUPERMARKET.PRODUCTOS (
	COD_BARRAS_EAN_13 NUMBER(13),
	COD_QR_ESTANTE VARCHAR(150),
	PRECIO NUMBER(3,2),
	STOCK NUMBER(2),
	INFORMACION NUTRICIONAL VARCHAR(300),
	ALERGENOS VARCHAR(200),
	TAG_ALTERNATIVAS VARCHAR(10),
	PHOTO_LOCATION VARCHAR(200),
	
	CONSTRAINT PK_COD_BARRAS_EAN_13 PRIMARY KEY (COD_BARRAS_EAN_13),
	CONSTRAINT FK_COD_QR_ESTANTE FOREIGN KEY (COD_QR_ESTANTE) REFERENCES ESTANTE(COD_QR_ESTANTE)	
);

CREATE TABLE IF NOT EXISTS CLIENTES (
	ID_CLIENTE NUMBER(100),
	NOMBRE VARCHAR(10),
	APELLIDOS VARCHAR(10),
	DOMICILIO VARCHAR(10),
	
	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS COMPRAS (
	ID_COMPRA NUMBER (100),
	COD_BARRAS_EAN_13 NUMBER(13),
	ID_CLIENTE NUMBER(100),
	CANTIDAD_PRODUCTO NUMBER(2),
	PRECIO_TOTAL NUMBER(3,2),
	FECHA_COMPRA DATE,
	
	CONSTRAINT PK_ID_COMPRA PRIMARY KEY (ID_COMPRA),
	CONSTRAINT FK_COD_BARRAS_EAN_13 FOREIGN KEY (COD_BARRAS_EAN_13) REFERENCES PRODUCTOS(COD_BARRAS_EAN_13)
	CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
);


