
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk
from GUI import scannerGUI

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def menuEscaneo(ventana):
    win_escaneo = tk.Toplevel(ventana)
    escaner = scannerGUI(win_escaneo)


window = Tk()

window.geometry("360x800")
window.configure(bg="#000000")

canvas = Canvas(
  window,
  bg="#000000",
  height=800,
  width=360,
  bd=0,
  highlightthickness=0,
  relief="ridge"
)

canvas.place(x=0, y=0)
button_image_1 = PhotoImage(
  file=relative_to_assets("button_1.png"))
button_1 = Button(
  image=button_image_1,
  borderwidth=0,
  highlightthickness=0,
  # Ejecución de comandos al hacer click
  command=lambda: print("button 1 clicked"),
  relief="flat"
)
button_1.place(
  x=34.0,
  y=613.0,
  width=290.0,
  height=64.0
)

button_image_2 = PhotoImage(
  file=relative_to_assets("button_2.png"))
button_2 = Button(
  image=button_image_2,
  borderwidth=0,
  highlightthickness=0,
  # Ejecución de comandos al hacer click
  command=lambda: print("button_2 clicked"),
  relief="flat"
)
button_2.place(
  x=34.0,
  y=544.0,
  width=290.0,
  height=61.0
)

button_image_3 = PhotoImage(
  file=relative_to_assets("button_3.png"))
button_3 = Button(
  image=button_image_3,
  borderwidth=0,
  highlightthickness=0,
  # Ejecución de comandos al hacer click
  command=lambda: menuEscaneo(window),
  relief="flat"
)
button_3.place(
  x=34.0,
  y=470.0,
  width=290.0,
  height=66.0
)

image_image_1 = PhotoImage(
  file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
  181.0,
  255.0,
  image=image_image_1
)
window.resizable(False, False)
window.mainloop()
