CREATE TABLE IF NOT EXISTS PASILLOS_ESTANTES (
	COD_QR_PASILLO_ESTANTE VARCHAR(150) NOT NULL,
	NOMBRE_PASILLO VARCHAR(40),
	DESCRIPCION VARCHAR(200),
	PHOTO_LOCATION VARCHAR(200),

	CONSTRAINT PK_COD_QR_PASILLO PRIMARY KEY (COD_QR_PASILLO_ESTANTE)
);

CREATE TABLE IF NOT EXISTS PRODUCTOS (
	COD_BARRAS_EAN_13 INT(13) NOT NULL,
	COD_QR_PASILLO_ESTANTE VARCHAR(150),
	NOMBRE VARCHAR(40),
	PRECIO DECIMAL(5,2), /*Indica 5 numeros de los cuales 2 son decimales*/
	STOCK SMALLINT(2),
	INFORMACION_NUTRICIONAL VARCHAR(300),
	ALERGENOS VARCHAR(200),
	TAG_ALTERNATIVAS VARCHAR(10),
	PHOTO_LOCATION VARCHAR(200),

	CONSTRAINT PK_COD_BARRAS_EAN_13 PRIMARY KEY (COD_BARRAS_EAN_13),
	CONSTRAINT FK_COD_QR_PASILLO_ESTANTE FOREIGN KEY (COD_QR_PASILLO_ESTANTE) REFERENCES PASILLOS_ESTANTES(COD_QR_PASILLO_ESTANTE)
);

CREATE TABLE IF NOT EXISTS CLIENTES (
	ID_CLIENTE INT(100) ZEROFILL NOT NULL,
	NOMBRE VARCHAR(10),
	APELLIDOS VARCHAR(10),
	DOMICILIO VARCHAR(100),

	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS COMPRAS (
	ID_COMPRA INT (100) ZEROFILL NOT NULL,
	COD_BARRAS_EAN_13 INT(13),
	ID_CLIENTE INT(100) ZEROFILL,
	CANTIDAD_PRODUCTO TINYINT(2),
	PRECIO_TOTAL DECIMAL(3,2),
	FECHA_COMPRA DATE,

	CONSTRAINT PK_ID_COMPRA PRIMARY KEY (ID_COMPRA),
	CONSTRAINT FK_COD_BARRAS_EAN_13 FOREIGN KEY (COD_BARRAS_EAN_13) REFERENCES PRODUCTOS(COD_BARRAS_EAN_13),
	CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);
